name: Distdeploy
on : [push,workflow_dispatch]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v6

            - name: install node 20
              uses: actions/checkout@v6
              with:
                node-version: 20

            - name: print node version
              run: node -v

            - name: cache dependecies
              uses: actions/cache@v5
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              

            - name: install dependecies
              run: npm ci

            - name: run test
              run: npm run test

    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v6

            - name: node install 20
              uses: actions/checkout@v6
              with:
                node-version: 20

            - name: cache dependecies
              uses: actions/cache@v5
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name : insall dependecies
              run: npm ci

            - name: build project
              run: npm run build
          

                   
              

        

