name: Distdeploy
on : 
    push:
        branches:
          - 'feature/**'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v6

            - name: install node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: print node version
              run: node -v

            - name: cache dependecies
              uses: actions/cache@v5
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
              

            - name: install dependecies
              run: npm ci

            - name: run test
              run: npm run test

    build:
        needs: test
        runs-on: ubuntu-latest
        steps:
            - name: get code
              uses: actions/checkout@v6

            - name: install node 20
              uses: actions/setup-node@v4
              with:
                node-version: 20

            - name: cache dependecies
              uses: actions/cache@v5
              with: 
                path: ~/.npm
                key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

            - name : insall dependecies
              run: npm ci

            - name: build project
              run: npm run build

            - name: upload dist artifact
              uses: actions/upload-artifact@v7
              with:
                name: dist files
                path: dist


    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
             - name: download dist artifact
               uses: actions/download-artifact@v8
               with:
                 name: dist files
                 path: dist
             - name: Deplou
               run: echo "Deploy successfully"
          

                   
              

        

